[pytest]

python_files =
    test_*.py
    *_test.py

python_classes =
    Test*

python_functions =
    test_*

addopts =
    -v
    -s

markers =
    user: тесты связанные с user
    regression: регрессионые тесты